#!/usr/bin/env bash

# SCRIPT_DIR is set to the directory where this script is localed. It it was
# run by a symlink, it will be resolved to the directory of the target script
# (that is, the actual script directory).
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
    SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_DIR}" )" >/dev/null 2>&1 && pwd )"
fi

# wm-get-workspace
#  - Print name of current workspace

# get platform info, populates 'platform' and 'apple_silicon' variables
source "${SCRIPT_DIR}"/lib/platform.sh


shopt -s xpg_echo

bold="\033[1m"
green="\033[32m"
reset="\033[0m"

# print usage message on -h/--help
if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "${bold}Usage:${reset} ${green}wm-workspace-get-current${reset}"
  echo "  - Print name of current workspace"
  exit 0
fi


if [[ "$platform" == "macos" ]]; then
  yabai -m query --spaces --space | jq '.index'
  exit $?
fi

# swaymsg, fallback to i3-msg
source "${SCRIPT_DIR}"/lib/swaymsg.sh

# get number of first empty workspace to the right of the current one
workspaces=$(swaymsg -t get_workspaces)
current_workspace=$(echo "${workspaces}" | jq '.[] | select(.focused==true).num')

echo "${current_workspace}"
