#!/usr/bin/env bash

# SCRIPT_DIR is set to the directory where this script is localed. It it was
# run by a symlink, it will be resolved to the directory of the target script
# (that is, the actual script directory).
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
    SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_DIR}" )" >/dev/null 2>&1 && pwd )"
fi

# get platform info, populates 'platform' and 'apple_silicon' variables
source "${SCRIPT_DIR}"/lib/platform.sh

# wm-workspace-kill-all
# - close all windows in all workspaces (except floating windows)

shopt -s xpg_echo

bold="\033[1m"
green="\033[32m"
reset="\033[0m"

# print usage with -h/--help
if [[ "$#" -eq 1 && ("$1" == "-h" || "$1" == "--help") ]]; then
    echo "${bold}Usage:${reset} ${green}wm-workspace-kill-all${reset}"
    echo "  - Close all windows in all workspaces (except floating windows)"
    exit 0
fi

if [[ "$platform" == "macos" ]]; then
  # first, close all other spaces
  non_focused_spaces=$(yabai -m query --spaces | jq -r '.[] | select(."has-focus"==false) | .index')
  for space in $non_focused_spaces; do
    yabai -m space --destroy $space
  done

  wm-workspace-kill
  exit
fi

# get all workspaces
workspaces=$(swaymsg -t get_workspaces | jq -r '.[] | .name')

# close all windows in all workspaces
for workspace in $workspaces; do
  windows=$(swaymsg -t get_tree | jq -r --arg workspace "$workspace" '.nodes[].nodes[] | select(.name==$workspace) | .nodes[].id')
  for window in $windows; do
    swaymsg '[con_id='$window'] kill'
  done
done

echo "Closed all windows in all workspaces (except floating windows)"
